import { padNumber } from '../../utils/helpers';
import type { RepoFileEntry } from '../../types/github.types';

// Render the repo's index README: a table of every solved problem, sorted by number.
export function generateReadme(repoName: string, entries: RepoFileEntry[]): string {
  const sorted = [...entries].sort((a, b) =>
    padNumber(a.number).localeCompare(padNumber(b.number)),
  );

  const rows = sorted
    .map((e) => {
      const folder = padNumber(e.number);
      const titleCell = e.url ? `[${e.title}](${e.url})` : e.title;
      const solutionCell = `[${e.language}](${e.solutionPath})`;
      return `| ${folder} | ${titleCell} | ${e.difficulty ?? '-'} | ${solutionCell} | ${e.solvedAt ?? '-'} |`;
    })
    .join('\n');

  return `# ${repoName}

> Auto-generated by [CodeVault](https://github.com/Gaurav06120714/CodeVault). Do not edit by hand.

**${sorted.length}** solved problem${sorted.length === 1 ? '' : 's'}.

| # | Problem | Difficulty | Solution | Solved |
|---|---------|------------|----------|--------|
${rows}
`;
}
